[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[dev]
  # This tells the Netlify dev server to run Astro's dev server
  command = "npm run dev"
  port = 8888
  targetPort = 4321 # Astro's default port
  framework = "astro"